#pragma once

// HybridChessEngine — the native (iOS + Android) implementation of the
// ChessEngine Nitro spec. It is a thin JSI facade that delegates to the
// header-only chess::Game core — the SAME C++ that compiles to WebAssembly for
// the web frontend (see bindings/web/chess_web.cpp). No engine internals cross
// the JS boundary; we speak only in board strings, square indices and a single
// result struct, so rendering stays cheap.
//
// `HybridChessEngineSpec` and the `MoveResult` struct are generated by nitrogen
// from src/ChessEngine.nitro.ts into nitrogen/generated/. The repo's core/
// directory must be on the include path (see README) so <game.hpp> resolves.

#include "HybridChessEngineSpec.hpp"
#include <game.hpp>

#include <string>
#include <vector>

namespace margelo::nitro::chessengine {

class HybridChessEngine : public HybridChessEngineSpec {
public:
  HybridChessEngine() : HybridObject(TAG) {}

  // --- setup --------------------------------------------------------------
  void reset() override { game_.reset(); }
  bool setFen(const std::string& fen) override { return game_.setFen(fen); }
  std::string fen() override { return game_.fen(); }

  // --- rendering ----------------------------------------------------------
  std::string boardString() override {
    std::string s(64, '.');
    for (int i = 0; i < 64; ++i) s[i] = chess::pieceGlyph(game_.pieceAt(i));
    return s;
  }
  double turn() override { return static_cast<double>(game_.turn()); }
  bool inCheck() override { return game_.inCheck(); }
  double ply() override { return static_cast<double>(game_.ply()); }
  double kingSquare(double color) override {
    const chess::Color c = (static_cast<int>(color) == 0) ? chess::WHITE : chess::BLACK;
    return static_cast<double>(game_.board().findKing(c));
  }

  // --- move input ---------------------------------------------------------
  std::vector<double> movesFrom(double square) override {
    std::vector<double> out;
    bool seen[64] = {false};
    for (const chess::Move& m : game_.legalMovesFrom(static_cast<int>(square))) {
      if (m.to < 0 || m.to >= 64 || seen[m.to]) continue;
      seen[m.to] = true;
      out.push_back(static_cast<double>(m.to));
    }
    return out;
  }
  bool isPromotion(double from, double to) override {
    const int t = static_cast<int>(to);
    for (const chess::Move& m : game_.legalMovesFrom(static_cast<int>(from)))
      if (m.to == t && (m.flag == chess::F_PROMO || m.flag == chess::F_PROMO_CAPTURE))
        return true;
    return false;
  }

  MoveResult doMove(double from, double to, const std::string& promo) override {
    MoveResult r;
    const int f = static_cast<int>(from);
    const int t = static_cast<int>(to);

    std::string uci = chess::squareName(f) + chess::squareName(t);
    if (!promo.empty()) uci += promo[0];

    chess::Move m;
    if (!game_.parseUci(uci, m)) {
      r.ok = false;
      r.from = from; r.to = to; r.san = "";
      r.capture = false; r.castle = false; r.promotion = false; r.enpassant = false;
      r.check = false; r.checkmate = false; r.gameOver = false;
      r.result = 0; r.drawReason = 0;
      r.board = boardString();
      return r;
    }

    const std::string san = game_.san(m); // SAN must be computed pre-move
    const bool capture   = m.isCapture();
    const bool castle    = (m.flag == chess::F_CASTLE_K || m.flag == chess::F_CASTLE_Q);
    const bool promotion = (m.flag == chess::F_PROMO || m.flag == chess::F_PROMO_CAPTURE);
    const bool enpassant = (m.flag == chess::F_EN_PASSANT);

    game_.push(m);

    r.ok = true;
    r.from = from; r.to = to;
    r.san = san;
    r.capture = capture; r.castle = castle;
    r.promotion = promotion; r.enpassant = enpassant;
    r.check = game_.inCheck();
    r.checkmate = game_.isCheckmate();
    r.gameOver = game_.isGameOver();
    r.result = static_cast<double>(game_.result());
    r.drawReason = static_cast<double>(game_.drawReason());
    r.board = boardString();
    return r;
  }

  // --- history ------------------------------------------------------------
  bool undo() override { return game_.undo(); }
  bool redo() override { return game_.redo(); }
  bool canUndo() override { return game_.canUndo(); }
  bool canRedo() override { return game_.canRedo(); }
  std::string lastMoveUci() override {
    const std::vector<std::string> h = game_.historyUci();
    return h.empty() ? std::string() : h.back();
  }

  // --- status -------------------------------------------------------------
  bool isGameOver() override { return game_.isGameOver(); }
  bool isCheckmate() override { return game_.isCheckmate(); }
  double result() override { return static_cast<double>(game_.result()); }
  double drawReason() override { return static_cast<double>(game_.drawReason()); }
  std::string pgn() override { return game_.pgnMovetext(); }
  std::vector<std::string> legalUci() override {
    const std::vector<std::string> v = game_.legalUci();
    return std::vector<std::string>(v.begin(), v.end());
  }

private:
  chess::Game game_;
};

} // namespace margelo::nitro::chessengine
